# -*- coding: utf-8 -*-
"""PART 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-uBteS_UeBn5GtqCZfM52q78QLj9c0B6
"""

# ===========================================================
# PART 2 — ELEMENTARY DATA STRUCTURES
# ===========================================================

# -----------------------------------------------------------
# ARRAY IMPLEMENTATION
# -----------------------------------------------------------

class Array:
    def __init__(self):
        self.data = []

    def insert(self, value):
        self.data.append(value)

    def delete(self, index):
        if 0 <= index < len(self.data):
            return self.data.pop(index)

    def access(self, index):
        return self.data[index] if 0 <= index < len(self.data) else None


# -----------------------------------------------------------
# STACK IMPLEMENTATION
# -----------------------------------------------------------

class Stack:
    def __init__(self):
        self.stack = []

    def push(self, value):
        self.stack.append(value)

    def pop(self):
        return self.stack.pop() if not self.is_empty() else None

    def peek(self):
        return self.stack[-1] if not self.is_empty() else None

    def is_empty(self):
        return len(self.stack) == 0


# -----------------------------------------------------------
# QUEUE IMPLEMENTATION
# -----------------------------------------------------------

class Queue:
    def __init__(self):
        self.queue = []

    def enqueue(self, value):
        self.queue.append(value)

    def dequeue(self):
        return self.queue.pop(0) if not self.is_empty() else None

    def is_empty(self):
        return len(self.queue) == 0


# -----------------------------------------------------------
# LINKED LIST IMPLEMENTATION
# -----------------------------------------------------------

class Node:
    def __init__(self, data):
        self.data = data
        self.next = None


class LinkedList:
    def __init__(self):
        self.head = None

    def insert(self, value):
        new_node = Node(value)

        if not self.head:
            self.head = new_node
            return

        temp = self.head
        while temp.next:
            temp = temp.next
        temp.next = new_node

    def delete(self, value):
        if not self.head:
            return

        if self.head.data == value:
            self.head = self.head.next
            return

        temp = self.head
        while temp.next and temp.next.data != value:
            temp = temp.next

        if temp.next:
            temp.next = temp.next.next

    def traverse(self):
        temp = self.head
        elements = []

        while temp:
            elements.append(temp.data)
            temp = temp.next

        return elements


# -----------------------------------------------------------
# FUNCTION CALLS (DEMO)
# -----------------------------------------------------------

if __name__ == "__main__":

    print("===== PART 2: DATA STRUCTURES =====")

    # ARRAY
    arr = Array()
    arr.insert(10)
    arr.insert(20)
    arr.insert(30)
    print("\nArray:", arr.data)
    print("Access index 1:", arr.access(1))
    arr.delete(1)
    print("Array after deletion:", arr.data)

    # STACK
    stk = Stack()
    stk.push(100)
    stk.push(200)
    print("\nStack peek:", stk.peek())
    print("Stack pop:", stk.pop())
    print("Stack:", stk.stack)

    # QUEUE
    q = Queue()
    q.enqueue(1)
    q.enqueue(2)
    print("\nQueue dequeue:", q.dequeue())
    print("Queue:", q.queue)

    # LINKED LIST
    ll = LinkedList()
    ll.insert(5)
    ll.insert(10)
    ll.insert(15)
    print("\nLinked List:", ll.traverse())
    ll.delete(10)
    print("Linked List after delete:", ll.traverse())



